# Site settings
# These are used to personalize your new site.
title: Zachary D. Weaver # your name here
logo: "/images/zachWeaver.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cybersecurity (class of 2025)
  <br /><br />
  <a href="/pdf/ZacharyWeaver_Resume.pdf" target="_blank">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/zach-weaver-084801261">View My LinkedIn Profile</a>
repository: "zachWeav/zachWeav.github.io"
github_username:  zachWeav # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

